#spring:
#  datasource:
#    url: jdbc:postgresql://localhost/baby_tracker
#    username: postgres
#    password: postgres
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
#    properties:
#      hibernate:
#        ddl-auto: update
#        jdbc:
#          lob:
#            non_contextual_creation: true
spring:
  datasource:
    url: postgres://qtyefwqniumhqy:8d74b058dd7635900d83664278b4f773aff7e23e0ab6c0b0175b85a7ae3639a6@ec2-52-3-60-53.compute-1.amazonaws.com:5432/dcskeoukdpm9fr
    username: qtyefwqniumhqy
    password: 8d74b058dd7635900d83664278b4f773aff7e23e0ab6c0b0175b85a7ae3639a6

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8099

